# Generated by Django 4.2.5 on 2023-10-30 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_fileupload_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fileupload',
        ),
    ]
