# Generated by Django 4.2.8 on 2023-12-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Project',
        ),
    ]
